resources:
- name: tutorial
  type: git
  source:
    uri: https://github.com/sham/concourse.git
    branch: master

- name: sham-powercli
  type: docker-image
  source:
    repository: 192.168.1.205:5000/sham-pcli
    tag: "latest"
    insecure_registries: [ "192.168.1.205:5000" ]

jobs:
- name: publish
  public: true
  plan:
  - get: tutorial
  - put: hello-world-docker-image
    params:
      build: tutorial/tutorials/miscellaneous/docker-images/docker
  - task: run
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: ((docker-hub-username))/concourse-tutorial-hello-world
      run:
        path: /bin/hello-world
        args: []
      params:
        NAME: ((docker-hub-username))